[package]
name = "wangxin-office"
version = "1.0.0"
description = "网信办公 · 轻量全格式办公文件读改工具"
authors = ["网信科技"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["macos-private-api"] }

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true
